# Generated by Django 5.1.6 on 2025-05-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('moviename', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('no_of_tickets', models.IntegerField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
